-- MySQL Script generated by MySQL Workbench
-- Sun Feb  2 14:03:52 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ReFresh` DEFAULT CHARACTER SET utf8 ;


-- -----------------------------------------------------
-- Table `SEDE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ReFresh`.`SEDE` (
  `id_sede` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `cp` INT NULL,
  `provincia` VARCHAR(45) NULL,
  `ciudad` VARCHAR(45) NULL,
  `calle` VARCHAR(45) NULL,
  PRIMARY KEY (`id_sede`));



-- -----------------------------------------------------
-- Table `DEPARTAMENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ReFresh`.`DEPARTAMENTO` (
  `id_dep` INT NOT NULL,
  `id_sede` INT NULL,
  `nombre` VARCHAR(45) NULL,
  `cp` INT NULL,
  `provincia` VARCHAR(45) NULL,
  `ciudad` VARCHAR(45) NULL,
  `calle` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`id_dep`),
  CONSTRAINT `id_sede`
    FOREIGN KEY (`id_sede`)
    REFERENCES `SEDE` (`id_sede`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);



-- -----------------------------------------------------
-- Table `TRABAJADORES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ReFresh`.`TRABAJADORES` (
  `dni` VARCHAR(20) NOT NULL,
  `fecha_ini` DATETIME NOT NULL,
  `id_dep` INT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellidos` VARCHAR(45) NULL,
  `tfno` INT NULL,
  `tfno_emergencia` INT NULL,
  `cp` INT NULL,
  `provincia` VARCHAR(45) NULL,
  `ciudad` VARCHAR(45) NULL,
  `calle` VARCHAR(45) NULL,
  `fecha_fin` DATETIME NULL,
  PRIMARY KEY (`dni`, `fecha_ini`),
  CONSTRAINT `id_dep`
    FOREIGN KEY (`id_dep`)
    REFERENCES `DEPARTAMENTO` (`id_dep`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);



-- -----------------------------------------------------
-- Table `ROLES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ReFresh`.`ROLES` (
  `dni` VARCHAR(20) NOT NULL,
  `id_rol` INT NOT NULL,
  `nombre_rol` VARCHAR(45) NULL,
  `descripcion` VARCHAR(100) NULL,
  PRIMARY KEY (`dni`, `id_rol`),
  CONSTRAINT `dni`
    FOREIGN KEY (`dni`)
    REFERENCES `TRABAJADORES` (`dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);



-- -----------------------------------------------------
-- Table `ADMINISTRACION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ReFresh`.`ADMINISTRACION` (
  `id_admin` INT NOT NULL,
  `nombre_adm` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nombre_adm`),
  CONSTRAINT `id_admin`
    FOREIGN KEY (`id_admin`)
    REFERENCES `DEPARTAMENTO` (`id_dep`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);



-- -----------------------------------------------------
-- Table `FABRICA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ReFresh`.`FABRICA` (
  `id_fab` INT NOT NULL,
  `nombre_fab` VARCHAR(45) NOT NULL,
  PRIMARY KEY ( `nombre_fab`),
  CONSTRAINT `id_fab`
    FOREIGN KEY (`id_fab`)
    REFERENCES `DEPARTAMENTO` (`id_dep`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);



-- -----------------------------------------------------
-- Table `PRODUCTOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ReFresh`.`PRODUCTOS` (
  `cod_barra` INT NOT NULL,
  `descuento` INT NULL,
  `sabor` VARCHAR(45) NULL,
  `marca` VARCHAR(45) NULL,
  `precio` FLOAT NULL,
  `cantidad` INT NULL,
  PRIMARY KEY (`cod_barra`));



-- -----------------------------------------------------
-- Table `FABRICA_PRODUCTOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ReFresh`.`FABRICA_PRODUCTOS` (
  `id_dep1` INT NOT NULL,
  `nombre_fab1` VARCHAR(45) NOT NULL,
  `cod_barra1` INT NOT NULL,
  PRIMARY KEY (`id_dep1`, `nombre_fab1`, `cod_barra1`),
  CONSTRAINT `id_dep1`
    FOREIGN KEY (`id_dep1`)
    REFERENCES `FABRICA` (`id_fab`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `nombre_fab1`
    FOREIGN KEY (`nombre_fab1`)
    REFERENCES `FABRICA` (`nombre_fab`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cod_barra1`
    FOREIGN KEY (`cod_barra1`)
    REFERENCES `PRODUCTOS` (`cod_barra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);



-- -----------------------------------------------------
-- Table `FORMULA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ReFresh`.`FORMULA` (
  `cod_barra` INT NOT NULL,
  `id_for` INT NOT NULL,
  `ingredientes` VARCHAR(45) NULL,
  `descripcion` VARCHAR(100) NULL,
  PRIMARY KEY (`cod_barra`, `id_for`),
  CONSTRAINT `cod_barra`
    FOREIGN KEY (`cod_barra`)
    REFERENCES `PRODUCTOS` (`cod_barra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);



-- -----------------------------------------------------
-- Table `CUPONES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ReFresh`.`CUPONES` (
  `cod_barra2` INT NOT NULL,
  `cod_cupon` INT NOT NULL,
  `desc_final` INT NULL,
  PRIMARY KEY (`cod_barra2`, `cod_cupon`),
  CONSTRAINT `cod_barra2`
    FOREIGN KEY (`cod_barra2`)
    REFERENCES `PRODUCTOS` (`cod_barra`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);



-- -----------------------------------------------------
-- Table `COMPRA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ReFresh`.`COMPRA` (
  `id_compra` INT NOT NULL,
  PRIMARY KEY (`id_compra`));



-- -----------------------------------------------------
-- Table `PRODUCTOS_COMPRA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ReFresh`.`PRODUCTOS_COMPRA` (
  `cod_barra3` INT NOT NULL,
  `id_compra1` INT NOT NULL,
  `cantidad` INT NULL,
  `fecha` DATETIME NULL,
  PRIMARY KEY (`cod_barra3`, `id_compra1`),
  CONSTRAINT `cod_barra3`
    FOREIGN KEY (`cod_barra3`)
    REFERENCES `PRODUCTOS` (`cod_barra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_compra1`
    FOREIGN KEY (`id_compra1`)
    REFERENCES `COMPRA` (`id_compra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);



-- -----------------------------------------------------
-- Table `FACTURA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ReFresh`.`FACTURA` (
  `id_compra` INT NOT NULL,
  `cod_fac` INT NOT NULL,
  `fecha_pago` DATETIME NULL,
  PRIMARY KEY (`id_compra`, `cod_fac`),
  CONSTRAINT `id_compra`
    FOREIGN KEY (`id_compra`)
    REFERENCES `COMPRA` (`id_compra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);



-- -----------------------------------------------------
-- Table `CLIENTES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ReFresh`.`CLIENTES` (
  `id_cliente` INT NOT NULL,
  `nombre_empresa` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`id_cliente`));



-- -----------------------------------------------------
-- Table `COMPRA_CLIENTES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ReFresh`.`COMPRA_CLIENTES` (
  `id_compra2` INT NOT NULL,
  `id_cliente1` INT NOT NULL,
  PRIMARY KEY (`id_compra2`, `id_cliente1`),
  CONSTRAINT `id_compra2`
    FOREIGN KEY (`id_compra2`)
    REFERENCES `COMPRA` (`id_compra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_cliente1`
    FOREIGN KEY (`id_cliente1`)
    REFERENCES `CLIENTES` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);



-- -----------------------------------------------------
-- Table `PRODUCTOS_CLIENTES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ReFresh`.`PRODUCTOS_CLIENTES` (
  `cod_barra4` INT NOT NULL,
  `id_cliente2` INT NOT NULL,
  PRIMARY KEY (`cod_barra4`, `id_cliente2`),
  CONSTRAINT `cod_barra4`
    FOREIGN KEY (`cod_barra4`)
    REFERENCES `PRODUCTOS` (`cod_barra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_cliente2`
    FOREIGN KEY (`id_cliente2`)
    REFERENCES `CLIENTES` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);



-- -----------------------------------------------------
-- Table `ESTRELLA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ReFresh`.`ESTRELLA` (
  `id_cliente_estrella` INT NOT NULL,
  `descuento` INT NULL,
  CONSTRAINT `id_cliente_estrella`
    FOREIGN KEY (`id_cliente_estrella`)
    REFERENCES `CLIENTES` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);



-- -----------------------------------------------------
-- Table `BASICOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ReFresh`.`BASICOS` (
  `id_cliente_basico` INT NOT NULL,
  CONSTRAINT `id_cliente_basico`
    FOREIGN KEY (`id_cliente_basico`)
    REFERENCES `CLIENTES` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
